defaults:
  - submitit_slurm

_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
timeout_min: 1200 # 20 hours
submitit_folder: ${hydra.sweep.dir}/.submitit/%j
tasks_per_node: 1
nodes: 1
name: ${hydra.job.name}
comment: null
exclude: null
additional_parameters: {}
array_parallelism: 256
gres: gpu:1
account: wgc@a100
cpus_per_task: 5
constraint: a100
