dataset:
  name: fleurons
  img_size: 128
model:
  name: dti_sprites
  n_sprites: 15
  n_backgrounds: 1
  n_objects: 1
  inject_noise: 0.4
  encoder_name: resnet32
  transformation_sequence: color
  transformation_sequence_bkg: color
  curriculum_learning: False
  curriculum_learning_bkg: False
  proto_init: constant
  bkg_init: constant
  mask_init: gaussian
  gaussian_weights_std: 25
  freeze_milestone: 0
  freeze_bkg: True
  freeze_frg: True
training:
  batch_size: 128
  n_workers: 4
  optimizer:
    name: adam
    lr: 1.0e-3
    transformer:
      weight_decay: 1.0e-6
  scheduler:
    name: multi_step
    gamma: 0.1
    milestones: [4500]
  n_epoches: 5000
  train_stat_interval: 50
  val_stat_interval: 100
  check_cluster_interval: 25
  seed: 2971
  visualizer_port:
