dataset:
  name: fleurons
  img_size: 128
model:
  name: dti_sprites
  n_sprites: 2
  n_backgrounds: 1
  n_objects: 1
  inject_noise: 0 
  encoder_name: resnet32
  transformation_sequence: color_affine_morpho
  transformation_sequence_bkg: color
  curriculum_learning: [100, 200] 
  curriculum_learning_bkg: False
  proto_init: constant
  bkg_init: constant
  mask_init: gaussian
  gaussian_weights_std: 25
  freeze_milestone: 0
  freeze_bkg: True
  freeze_frg: True
training:
  batch_size: 64
  n_workers: 4
  optimizer:
    name: adam
    lr: 1.0e-3
    transformer:
      weight_decay: 1.0e-6
  scheduler:
    name: multi_step
    gamma: 0.1
    milestones: [250]
  n_epoches: 300
  train_stat_interval: 100
  val_stat_interval: 100
  check_cluster_interval: 100
  seed: 2971
  n_dup: 6
  resume: 0315_hier_2_morpho_0
  visualizer_port:
