dataset:
  name: coa
  tag: simple-eagle-edited
  img_size: 128
model:
  name: dti_sprites
  n_sprites: 5
  n_backgrounds: 1
  n_objects: 1
  inject_noise: 0 
  prototype:
    source: data # or generator
    generator: unet # or mlp
    data:
      init: [constant, soup, gaussian] # initializations of fg, bkg, mask in pixels space
      gaussian_weights_std: 25
      freeze: [True, False, False] # to freeze fg, bkg, mask
      freeze_milestone: 0 # when to freeze
    proba: False # or linear, network
    shared_latent: False # shared latent for proba and generator
  encoder_name: resnet32
  transformation_sequence: color_affine_morpho_tps
  transformation_sequence_bkg: color_affine
  curriculum_learning: [100, 300, 350] 
  curriculum_learning_bkg: [100]
training:
  batch_size: 32
  n_workers: 4
  optimizer:
    name: adam
    lr: 1.0e-3
    transformer:
      weight_decay: 1.0e-6
  scheduler:
    name: multi_step
    gamma: 0.1
    milestones: [375]
  n_epoches: 400
  train_stat_interval: 50
  val_stat_interval: 50
  check_cluster_interval: 50
  seed: 2971
  n_dup: 0
  visualizer_port:
