dataset:
  name: instagram
  tag: santaphoto
model:
  name: dti_sprites
  n_sprites: 40
  n_backgrounds: 1
  inject_noise: 0.4
  encoder_name: resnet18
  transformation_sequence: color_projective
  transformation_sequence_bkg: color_projective
  curriculum_learning: [100]
  curriculum_learning_bkg: [100]
  proto_init: constant
  mask_init: gaussian
  bkg_init: mean
  gaussian_weights_std: 20
training:
  batch_size: 32
  optimizer:
    name: adam
    lr: 1.0e-3
    transformer:
      weight_decay: 1.0e-6
  scheduler:
    name: multi_step
    gamma: 0.1
    milestones: [700]
  n_epoches: 850
  train_stat_interval: 1000
  val_stat_interval: 2000
  check_cluster_interval: 250
  seed: 32903
  visualizer_port:
  pretrained: 
  resume:
