batch_size: 32
n_workers: 4
optimizer:
  lr: 1.0e-4
scheduler:
  gamma: [1, 0.1]
  milestones: [750, 900]
n_epochs: 1000
train_stat_interval: 1000
val_stat_interval: 2000
check_cluster_interval: 1000
