dataset:
  name: affnist_test
model:
  name: dti_sprites
  n_sprites: 10
  n_backgrounds: 0 #1
  n_objects: 1
  prototype:
    source: generator
    generator: mlp
    data:
      freeze: [True, True, False]
      init: ["constant", "constant", "random"]
      value: [1., 0., 0.]
  encoder_name: resnet20
  color_channels: 1
  transformation_sequence: identity_affine_morpho_tps
  transformation_sequence_bkg: identity
  curriculum_learning: [5, 20, 25]
  curriculum_learning_bkg: False
  grid_size: 4
  kernel_size: 7
  freeze_frg: True
training:
  batch_size: 128
  optimizer:
    name: adam
    lr: 1.0e-4
    transformer:
      lr: 5.0e-4
      weight_decay: 1.0e-6
  scheduler:
    name: multi_step
    gamma: 0.1
    milestones: [37]
    update_range: epoch
  n_epoches: 45
  train_stat_interval: 200
  val_stat_interval: 400
  check_cluster_interval: 400
  seed: 68401
  visualizer_port: 
