dataset:
  name: fashion_mnist
model:
  name: dti_sprites
  n_sprites: 10
  n_backgrounds: 0 #1
  n_objects: 1
  inject_noise: 0
  prototype:
    source: generator
    generator: mlp
    data:
      freeze: [True, True, False]
      init: ["constant", "constant", "random"]
      value: [1., 0., 0.]
  encoder_name: resnet20
  color_channels: 1
  transformation_sequence: identity_color_affine_tps
  curriculum_learning: [5, 15, 25]
  grid_size: 4
training:
  batch_size: 128
  optimizer:
    name: adam
    lr: 1.0e-3
    transformer:
      weight_decay: 1.0e-6
  scheduler:
    name: multi_step
    gamma: 0.1
    milestones: [35]
    update_range: epoch
  n_epoches: 40
  train_stat_interval: 25
  val_stat_interval: 50
  check_cluster_interval: 50
  seed: 79597
  visualizer_port:
