dataset:
  name: gtsrb8
model:
  name: dti_sprites
  n_sprites: 8
  n_backgrounds: 1
  inject_noise: 0.4
  prototype:
    source: generator
    generator: mlp
    data:
      gaussian_weights_std: 5
  encoder_name: resnet32
  transformation_sequence: color_projective_tps
  transformation_sequence_bkg: color_projective_tps
  curriculum_learning: [400, 1400]
  curriculum_learning_bkg: [400, 1400]
  init_latent_linear: gaussian
  init_bkg_linear: mean
  proba: True
  proba_type: linear
  reassign_cluster: False
  freq_weight: 0.1
training:
  batch_size: 128
  n_workers: 4
  optimizer:
    name: adam
    lr: 1.0e-3
    transformer:
      weight_decay: 1.0e-6
  scheduler:
    name: multi_step
    gamma: 0.1
    milestones: [2400]
  n_epoches: 2800
  train_stat_interval: 100
  val_stat_interval: 200
  check_cluster_interval: 25
  seed: 54942
  visualizer_port:
  pretrained: 
  resume: 
