dataset:
  name: gtsrb8
model:
  name: dti_sprites
  n_sprites: 8
  n_backgrounds: 1
  inject_noise: 0.4
  prototype:
    source: data
    data:
      freeze: [False, False, False]
      init: ["constant", "mean", "gaussian"]
      value: [0.9, 0., 0.]
      gaussian_weights_std: 5
  encoder_name: resnet32
  transformation_sequence: color_projective_tps
  transformation_sequence_bkg: color_projective_tps
  curriculum_learning: [100, 350]
  curriculum_learning_bkg: [100, 350]
training:
  batch_size: 128
  n_workers: 4
  optimizer:
    name: adam
    lr: 5.0e-3
    transformer:
      lr: 1.0e-2
      weight_decay: 1.0e-6
  scheduler:
    name: multi_step
    gamma: 0.1
    milestones: [600]
  n_epoches: 700
  train_stat_interval: 1000
  val_stat_interval: 2000
  check_cluster_interval: 25
  seed: 27948
  visualizer_port:
  pretrained: 
  resume: 
