dataset:
  name: weizmann_horse
model:
  name: dti_sprites
  n_sprites: 1
  n_backgrounds: 1
  inject_noise: 0.4
  encoder_name: resnet18
  transformation_sequence: color_projective_tps
  transformation_sequence_bkg: color_projective_tps
  curriculum_learning: [3000, 8000]
  curriculum_learning_bkg: [3000, 8000]
  proto_init: constant
  mask_init: gaussian
  bkg_init: mean
  gaussian_weights_std: 20
training:
  batch_size: 32
  n_workers: 6
  optimizer:
    name: adam
    lr: 1.0e-3
    transformer:
      weight_decay: 1.0e-6
  scheduler:
    name: multi_step
    gamma: 0.1
    milestones: [14000]
  n_epoches: 15000
  train_stat_interval: 300
  val_stat_interval: 600
  check_cluster_interval: 300
  seed: 3830
  visualizer_port:
  pretrained: 
  resume:
