dataset:
  name: Lettre_a
  img_size: 32
model:
  name: dti_sprites
  n_sprites: 10
  n_backgrounds: 1
  n_objects: 1
  inject_noise: 0 
  prototype:
    source: data
    data:
      freeze: [True, True, False]
      value: [0.1, 0.9, 0.]
      init: ["constant", "constant", "random"]
  encoder_name: resnet32
  transformation_sequence: color_affine #_morpho_tps
  transformation_sequence_bkg: color_affine
  curriculum_learning: [200] #, 350, 400]
  curriculum_learning_bkg: [200]
training:
  batch_size: 64
  n_workers: 4
  optimizer:
    name: adam
    lr: 1.0e-3
    transformer:
      weight_decay: 1.0e-6
  scheduler:
    name: multi_step
    gamma: 0.1
    milestones: [450]
  n_epoches: 500
  train_stat_interval: 100
  val_stat_interval: 100
  check_cluster_interval: 100
  seed: 2971
  n_dup: 0
  visualizer_port:
