dataset:
  name: mnist
model:
  name: dti_sprites
  n_sprites: 10
  n_backgrounds: 0
  n_objects: 1
  prototype:
    source: generator
    generator: mlp
    data:
      freeze: [True, True, False]
      init: ["constant", "constant", "random"]
      value: [1., 0., 0.]
  encoder_name: resnet20
  color_channels: 1
  transformation_sequence: identity_affine_morpho_tps
  transformation_sequence_bkg: identity
  curriculum_learning: [10, 30, 40]
  curriculum_learning_bkg: False
  grid_size: 4
  kernel_size: 7
  proba: True
  proba_type: linear
  reassign_cluster: False
  freq_weight: 0.0

training:
  batch_size: 128
  optimizer:
    name: adam
    lr: 1.0e-3
    transformer:
      weight_decay: 1.0e-6
  scheduler:
    name: multi_step
    gamma: 0.1
    milestones: [70]
    update_range: epoch
  n_epoches: 80
  train_stat_interval: 25
  val_stat_interval: 50
  check_cluster_interval: 50
  seed: 66247
  visualizer_port:
