dataset:
  name: svhn
model:
  name: dti_sprites
  n_sprites: 10
  n_backgrounds: 1
  inject_noise: 0.4
  prototype:
    source: generator
    generator: mlp
    data:
      freeze: [0, 0, 5]
      gaussian_weights_std: 8
  encoder_name: resnet32
  transformation_sequence: color_projective_tps
  transformation_sequence_bkg: color_projective_tps
  curriculum_learning: [10, 35]
  curriculum_learning_bkg: [10, 35]
  init_latent_linear: gaussian
  init_bkg_linear: mean
training:
  batch_size: 128
  n_workers: 4
  optimizer:
    name: adam
    lr: 5.0e-3
    transformer:
      weight_decay: 1.0e-6
  scheduler:
    name: multi_step
    gamma: 0.1
    milestones: [50]
  n_epoches: 55
  train_stat_interval: 10000
  val_stat_interval: 10000
  check_cluster_interval: 100
  seed: 99175
  visualizer_port:
  pretrained:
  resume:
