dataset:
  name: svhn
model:
  name: dti_sprites
  n_sprites: 10
  n_backgrounds: 1
  n_objects: 1
  prototype:
    source: generator
    generator: mlp
    data:
      freeze: [False, False, False]
      init: ["", "", ""]
  encoder_name: resnet32
  transformation_sequence: identity_color_projective
  transformation_sequence_bkg: identity_color_projective
  curriculum_learning: [10, 35]
  curriculum_learning_bkg: [10, 35]
training:
  batch_size: 128
  n_workers: 4
  optimizer:
    name: adam
    lr: 1.0e-3
    transformer:
      weight_decay: 1.0e-6
  scheduler:
    name: multi_step
    gamma: 0.1
    milestones: [50]
  n_epoches: 55
  train_stat_interval: 500
  val_stat_interval: 1000
  check_cluster_interval: 100
  seed: 62130
  visualizer_port:
  pretrained:
  resume:
