dataset:
  name: tetrominoes
model:
  name: dti_sprites
  n_sprites: 19
  n_backgrounds: 0
  n_objects: 3
  inject_noise: 0.4
  prototype:
    source: data
    data:
      freeze: [0, 0, 1]
      init: ["constant", "constant", "gaussian"]
      value: [0.9, 0., 0.]
      gaussian_weights_std: 5
  encoder_name: resnet32
  transformation_sequence: identity
  transformation_sequence_bkg: color
  transformation_sequence_layer: color_position
  curriculum_learning: False
  curriculum_learning_bkg: False
  curriculum_learning_layer: False
  sprite_size: [24, 24]
  pred_occlusion: False
  estimate_minimum: True
  greedy_algo_iter: 1
training:
  batch_size: 32
  n_workers: 8
  optimizer:
    name: adam
    lr: 1.0e-4
    transformer:
      weight_decay: 1.0e-6
  scheduler:
    name: multi_step
    gamma: [1, 0.1]
    milestones: [100, 200]
  n_epochs: 210
  train_stat_interval: 500
  val_stat_interval: 100
  check_cluster_interval: 50
  eval_with_bkg: True
  eval_semantic: True
  seed: 48480
  visualizer_port:
  pretrained: 
  resume: 
