dataset:
  name: tetrominoes
model:
  name: dti_sprites
  n_sprites: 19
  n_backgrounds: 0
  n_objects: 3
  inject_noise: 0.4
  color_channels: 1
  prototype:
    source: generator
    generator: mlp
    data:
      freeze: [300, 0, 1]
      init: ["constant", "constant", "gaussian"]
      value: [0.9, 0., 0.]
      gaussian_weights_std: 5
  softmax: softmax
  encoder_name: resnet32
  transformation_sequence: identity
  transformation_sequence_bkg: linearcolor
  transformation_sequence_layer: linearcolor_translation
  curriculum_learning: False
  curriculum_learning_bkg: False
  curriculum_learning_layer: False
  init_latent_linear: gaussian
  sprite_size: [24, 24]
  pred_occlusion: False
  estimate_minimum: True
  reassign_cluster: False
  proba: True
  proba_type: linear
  freq_weight: 0.0
  bin_weight: 0.001
training:
  batch_size: 32
  n_workers: 8
  optimizer:
    name: adam
    lr: 1.0e-4
    transformer:
      weight_decay: 1.0e-6
  scheduler:
    name: multi_step
    gamma: [1, 0.1]
    milestones: [500, 600] 
  n_epochs: 610
  train_stat_interval: 1000
  val_stat_interval: 2000
  check_cluster_interval: 50
  eval_with_bkg: True
  eval_semantic: True
  seed: 24937
  visualizer_port:
  pretrained:
