dataset:
  name: affnist_test
model:
  name: dtikmeans
  n_prototypes: 10
  prototype:
    source: generator
    generator: mlp
  encoder_name: resnet20
  color_channels: 1
  transformation_sequence: identity_affine_morpho_tps
  curriculum_learning: [20, 50, 55] # + 15, +15
  grid_size: 4
  kernel_size: 7
  proba: True
  proba_weighting: diff
  proba_type: linear
  reassign_cluster: False
  freq_weight: 10
  empty_cluster_threshold: 0.05
training:
  batch_size: 128
  optimizer:
    name: adam
    lr: 1.0e-4
    transformer:
      weight_decay: 1.0e-6
  scheduler:
    name: multi_step
    gamma: 0.1
    milestones: [67]
    update_range: epoch
  n_epoches: 75
  train_stat_interval: 200
  val_stat_interval: 400
  check_cluster_interval: 400
  seed: 4006
  visualizer_port: 
