dataset:
  name: affnist_test
model:
  name: dtikmeans
  n_prototypes: 10
  prototype:
    source: data
    data:
      init: sample
  encoder_name: resnet20
  transformation_sequence: identity_affine_morpho_tps
  curriculum_learning: [5, 20, 25]
  grid_size: 4
  kernel_size: 7
training:
  batch_size: 128
  sprite_optimizer:
    name: sgd
    lr: 1.0e-4
  optimizer:
    name: adam
    lr: 1.0e-4
    transformer:
      weight_decay: 1.0e-6
  scheduler:
    name: multi_step
    gamma: 0.1
    milestones: [37]
    update_range: epoch
  n_epochs: 45
  train_stat_interval: 200
  val_stat_interval: 400
  check_cluster_interval: 400
  seed: 89190
  visualizer_port: 
