dataset:
  name: fashion_mnist
model:
  name: dtikmeans
  n_prototypes: 10
  prototype:
    source: generator
    generator: mlp
  encoder_name: resnet20
  color_channels: 1
  transformation_sequence: identity_color_affine_tps
  curriculum_learning: [20, 30, 40] # + 15
  grid_size: 4
  proba: True
  proba_weighting: diff
  proba_type: linear
  reassign_cluster: False
  freq_weight: 0
training:
  batch_size: 128
  optimizer:
    name: adam
    lr: 1.0e-3
    transformer:
      weight_decay: 1.0e-6
  scheduler:
    name: multi_step
    gamma: 0.1
    milestones: [50]
    update_range: epoch
  n_epoches: 55
  train_stat_interval: 25
  val_stat_interval: 50
  check_cluster_interval: 50
  seed: 97784
  visualizer_port:
