dataset:
  name: fleurons
  img_size: 256 #128
model:
  name: dtikmeans
  n_prototypes: 36
  prototype:
    source: data
    data:
      init: gaussian
      gaussian_weights_std: 25
  encoder_name: resnet20
  transformation_sequence: identity_color_affine
  curriculum_learning: [600, 800]
  #empty_cluster_threshold: 0.01
training:
  batch_size: 16 #64
  optimizer:
    name: adam
    lr: 1.0e-3
    transformer:
      weight_decay: 1.0e-6
  scheduler:
    name: multi_step
    gamma: 0.1
    milestones: [1200]
    update_range: epoch
  n_epochs: 1500
  train_stat_interval: 100
  val_stat_interval: 100
  check_cluster_interval: 50
  seed: 7832
  visualizer_port:
