dataset:
  name: frgc
model:
  name: dtikmeans
  n_prototypes: 20
  prototype:
    source: generator
    generator: mlp
    proba: True
    proba_type: weight_sprite
    lambda_freq: 0.
    shared_latent: True
  encoder_name: resnet20
  transformation_sequence: identity_color_affine_tps
  curriculum_learning: [50, 200, 400]
  grid_size: 4
  reassign_cluster: False
training:
  batch_size: 128
  optimizer:
    name: adam
    lr: 1.0e-3
    transformer:
      weight_decay: 1.0e-6
  scheduler:
    name: multi_step
    gamma: 0.1
    milestones: [650]
    update_range: epoch
  n_epoches: 700
  train_stat_interval: 10
  val_stat_interval: 20
  check_cluster_interval: 20
  seed: 23818
  visualizer_port: 
