dataset:
  name: frgc
model:
  name: dtikmeans
  n_prototypes: 20
  prototype:
    source: data
    data:
      init: sample
  encoder_name: resnet20
  transformation_sequence: identity_color_affine_tps
  curriculum_learning: [50, 200, 400]
  grid_size: 4
training:
  batch_size: 128
  sprite_optimizer:
    name: sgd
    lr: 1.0e-3
  optimizer:
    name: adam
    lr: 1.0e-3
    transformer:
      weight_decay: 1.0e-6
  scheduler:
    name: multi_step
    gamma: 0.1
    milestones: [650]
    update_range: epoch
  n_epoches: 700
  train_stat_interval: 10
  val_stat_interval: 20
  check_cluster_interval: 20
  seed: 20932
  visualizer_port: 