dataset:
  name: gtsrb8
model:
  name: dtikmeans
  n_prototypes: 8
  prototype:
    source: generator
    generator: mlp
  encoder_name: resnet20
  transformation_sequence: identity_color_projective
  curriculum_learning: [20, 180]
  gaussian_weights: True
  gaussian_weights_std: 7
training:
  batch_size: 128
  n_workers: 4
  optimizer:
    name: adam
    lr: 1.0e-3
    transformer:
      weight_decay: 1.0e-6
  scheduler:
    name: multi_step
    gamma: 0.1
    milestones: [300]
  n_epochs: 330
  train_stat_interval: 100
  val_stat_interval: 200
  check_cluster_interval: 25
  seed: 12216
  visualizer_port:
  pretrained: 
  resume: 
