dataset:
  name: gtsrb8
model:
  name: dtikmeans
  n_prototypes: 8
  prototype:
    source: generator
    generator: mlp
  encoder_name: resnet20
  transformation_sequence: identity_color_projective
  curriculum_learning: [40, 360]
  gaussian_weights: True
  gaussian_weights_std: 7
  proba: True
  proba_weighting: diff
  proba_type: linear
  reassign_cluster: False
  freq_weight: 0
training:
  batch_size: 128
  n_workers: 4
  optimizer:
    name: adam
    lr: 1.0e-3
    transformer:
      weight_decay: 1.0e-6
  scheduler:
    name: multi_step
    gamma: 0.1
    milestones: [600]
  n_epoches: 660
  train_stat_interval: 100
  val_stat_interval: 200
  check_cluster_interval: 25
  seed: 63952
  visualizer_port:
  pretrained: 
  resume: 
