dataset:
  name: mnist_color
model:
  name: dtikmeans
  n_prototypes: 10
  prototype:
    source: generator
    generator: mlp
  encoder_name: resnet20
  transformation_sequence: identity_color_affine_tps
  curriculum_learning: [10, 30, 60]
  grid_size: 4
  proba: True
  proba_weighting: tr_sprite
  proba_type: linear
  reassign_cluster: False
  freq_weight: 0.
  empty_cluster_threshold: 0.05
training:
  batch_size: 128
  optimizer:
    name: adam
    lr: 1.0e-3
    transformer:
      weight_decay: 1.0e-6
  scheduler:
    name: multi_step
    gamma: 0.1
    milestones: [90]
    update_range: epoch
  n_epoches: 100
  train_stat_interval: 25
  val_stat_interval: 50
  check_cluster_interval: 50
  seed: 95893
  visualizer_port:
