dataset:
  name: mnist_color
model:
  name: dtikmeans
  n_prototypes: 10
  prototype:
    source: generator
    generator: marionette
  encoder_name: resnet20
  transformation_sequence: identity_color_affine_tps
  curriculum_learning: [5, 35, 50]
  grid_size: 4
training:
  batch_size: 128
  optimizer:
    name: adam
    lr: 1.0e-3
    transformer:
      weight_decay: 1.e-6
  scheduler:
    name: multi_step
    gamma: 0.1
    milestones: [65]
    update_range: epoch
  n_epoches: 70
  train_stat_interval: 25
  val_stat_interval: 50
  check_cluster_interval: 50
  seed: 36193
  visualizer_port:
