dataset:
  name: mnist
model:
  name: dtikmeans
  n_prototypes: 10
  prototype:
    source: generator
    generator: mlp
  encoder_name: resnet20
  color_channels: 1
  transformation_sequence: identity_affine_morpho_tps
  curriculum_learning: [20, 30, 35]
  grid_size: 4
  kernel_size: 7
  proba: True
  proba_weighting: diff
  proba_type: marionette
  reassign_cluster: False
  shared_l: False
training:
  batch_size: 128
  optimizer:
    name: adam
    lr: 1.0e-3
    transformer:
      weight_decay: 1.0e-6
  scheduler:
    name: multi_step
    gamma: 0.1
    milestones: [50]
    update_range: epoch
  n_epoches: 55
  train_stat_interval: 25
  val_stat_interval: 50
  check_cluster_interval: 50
  seed: 2332
  visualizer_port: 