dataset:
  name: mnist
model:
  name: dtikmeans
  n_prototypes: 10
  prototype:
    source: generator
    generator: marionette
    proba: True
    proba_type: weight_diff
  encoder_name: resnet20
  color_channels: 1
  transformation_sequence: identity_affine #_morpho_tps
  curriculum_learning: [65] #[30, 40, 45] #[5, 15, 20]
  grid_size: 4
  kernel_size: 7
  reassign_cluster: False 
training:
  batch_size: 128
  optimizer:
    name: adam
    lr: 1.e-3
    transformer:
      weight_decay: 1.0e-6
  scheduler:
    name: multi_step
    gamma: 0.1
    milestones: [65] #[35]
    update_range: epoch
  n_epoches: 60 #40
  train_stat_interval: 25
  val_stat_interval: 50
  check_cluster_interval: 50
  seed: 92951
  visualizer_port:
