dataset:
  name: usps
model:
  name: dtikmeans
  n_prototypes: 10
  prototype:
    source: generator
    generator: mlp
  encoder_name: resnet20
  color_channels: 1
  transformation_sequence: identity_color_affine_tps
  curriculum_learning: [120, 240, 400]
  grid_size: 4
  padding_mode: zeros
  proba: True
  proba_weighting: tr_sprite
  proba_type: linear
  reassign_cluster: False
  empty_cluster_threshold: 0.05
  freq_weight: 0.0
  bin_weight: 1.
training:
  batch_size: 128
  optimizer:
    name: adam
    lr: 1.0e-3
    transformer:
      weight_decay: 1.0e-6
  scheduler:
    name: multi_step
    gamma: 0.1
    milestones: [500]
    update_range: epoch
  n_epoches: 540
  train_stat_interval: 25
  val_stat_interval: 50
  check_cluster_interval: 50
  seed: 13909
  visualizer_port:
