dataset:
  name: usps
model:
  name: dtikmeans
  n_prototypes: 10
  prototype:
    source: generator
    generator: mlp
    proba: True
    proba_type: weight_diff
    lambda_freq: 0.
    shared_latent: True
  encoder_name: resnet20
  color_channels: 1
  transformation_sequence: identity_color_affine_tps
  curriculum_learning: [60, 120, 200]
  grid_size: 4
  padding_mode: zeros
  reassign_cluster: False
training:
  batch_size: 128
  optimizer:
    name: adam
    lr: 1.0e-3
    transformer:
      weight_decay: 1.0e-6
  scheduler:
    name: multi_step
    gamma: 0.1
    milestones: [250]
    update_range: epoch
  n_epoches: 270
  train_stat_interval: 25
  val_stat_interval: 50
  check_cluster_interval: 50
  seed: 49422
  visualizer_port:
